version: '3.4'

services:
  proxy:
    image: nginx
    volumes:
      - ./proxy/templates:/etc/nginx/templates
      - ./client/public:/usr/share/nginx/html
    ports:
      - 8080:80
    environment:
      - NGINX_HOST=node.first
      - NGINX_PORT=80

  client:
    image: library/node:14.15-alpine
    user: node
    working_dir: /home/node/app
    ports:
      - 3000:3000
    volumes:
      - ./client:/home/node/app
    command: "npm run start"
    tty: true

  server:
    image: library/node:14.15-alpine
    user: node
    working_dir: /home/node/app
    volumes:
      - ./server:/home/node/app
    ports:
    - 8081:8080
    command: "npm run start"
    depends_on:
      - db
  db:
    image: library/mongo:4.4.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
